### ISSUE TITLE
Removing players from team as team captain does not check validation status

### ISSUE THREAD

**Issue by Skymirrh** [InsaLan/insalan.fr#26]
If a captain removes players from a team that has already been validated, the team can end up in a state ineligible for validation (i.e. less than the required number of players, or less than the required number of paid players), but currently it is not invalidated.

Example: https://www.insalan.fr/tournament/9/public/team
![2015-11-19_11-46-44](https://cloud.githubusercontent.com/assets/4659919/11268833/5864e228-8eb3-11e5-98a5-3045cd6d98cb.png)

**Comment by halfa** [comment]
This is an edge case related to free tournaments.
I'll fix this asap. Thanks for the report.
