### ISSUE TITLE
Add date/year on old tournament reports

### ISSUE THREAD

**Issue by FoxyHawk** [InsaLan/insalan.fr#70]
Improve clarity when reading old tournament report

**Comment by FoxyHawk** [comment]
For exemple, not any year given for this tournament

![tournament](https://user-images.githubusercontent.com/37553238/48210170-1d7aca80-e377-11e8-90cd-afb41c9c0617.png)

**Comment by AntoineBvn** [comment]
You think about adding date (like "February 2018") or InsaLan's edition (like "InsaLan 13" or "InsaLan 2018") ?
