### ISSUE TITLE
Default values used during install

### ISSUE THREAD

**Issue by FoxyHawk** [InsaLan/insalan.fr#75]
The following values **must** be changed from 'null' to 'xxxx' to keep consistency (raise fatal error during install) :

-  paypal_express_checkout_username
-  paypal_express_checkout_password
-  paypal_express_checkout_signature

The following values **should** be changed from 'insalan.fr' to 'insalan' to keep consistency with mariadb naming best pratices :

- database_name
- database_user

**Comment by AntoineBvn** [comment]
Thanks for warning us.
Consider it done.
